version: '3.8'
services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: chatflow
      POSTGRES_PASSWORD: chatflow123
      POSTGRES_DB: chatflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: